services:
  app:
    network_mode: host
    build: .
    env_file:
      - backend/.env
    environment:
      STORAGE_ROOT: /app/storage
      GIN_MODE: release
    volumes:
      - alphaguard_storage:/app/storage
      - ./backend/.env:/app/.env:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  alphaguard_storage:
